events {}
http {
    include /etc/nginx/mime.types;
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ =404;
        }
        location /api/ {
            # 끝에 /를 붙이지 않아 /api/ 경로를 그대로 전달합니다.
            proxy_pass http://week5_api01:5000;
            proxy_set_header Host $host;
        }
    }
}
